### ISSUE TITLE
Can't copy Cross Entropy formula in Word

### ISSUE THREAD

**Issue by DarkSkull91** [Foxxey/CopyEquation#2]
Hi, when I try to copy the cross entropy function in Word instead of the formula I get this:
`<math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mtext>Cross&nbsp;Entropy</mtext><mo>=</mo><mo>−</mo><mfrac><mn>1</mn><mi>n</mi></mfrac><msubsup><mo>∑</mo><mrow><mi>i</mi><mo>=</mo><mn>1</mn></mrow><mi>n</mi></msubsup><mrow><mo fence="true">[</mo><msub><mi>y</mi><mi>i</mi></msub><mi>log</mi><mo>⁡</mo><mo stretchy="false">(</mo><msub><mover accent="true"><mi>y</mi><mo>^</mo></mover><mi>i</mi></msub><mo stretchy="false">)</mo><mo>+</mo><mo stretchy="false">(</mo><mn>1</mn><mo>−</mo><msub><mi>y</mi><mi>i</mi></msub><mo stretchy="false">)</mo><mi>log</mi><mo>⁡</mo><mo stretchy="false">(</mo><mn>1</mn><mo>−</mo><msub><mover accent="true"><mi>y</mi><mo>^</mo></mover><mi>i</mi></msub><mo stretchy="false">)</mo><mo fence="true">]</mo></mrow></mrow><annotation encoding="application/x-tex">\text{Cross Entropy} = -\frac{1}{n} \sum_{i=1}^{n} \left[ y_i \log(\hat{y}_i) + (1 - y_i) \log(1 - \hat{y}_i) \right]</annotation></semantics></math>`

Probably the addon doesn't parse well the code given by ChatGPT, that is:
`\[ \text{Cross Entropy} = -\frac{1}{n} \sum_{i=1}^{n} \left[ y_i \log(\hat{y}_i) + (1 - y_i) \log(1 - \hat{y}_i) \right] \]`

**Comment by Foxxey** [comment]
Should be fixed now.

**Comment by DarkSkull91** [comment]
Awsome! It works like a charm, thanks!
